import json
import os
import glob
import argparse
from reportlab.pdfgen import canvas

# --- ARGUMENT PARSING ---
parser = argparse.ArgumentParser(description="Convert Marker JSON to HTML/PDF bounding boxes.")
parser.add_argument("--input", required=True, help="Directory containing Marker JSON output")
parser.add_argument("--output", required=True, help="Directory to save final HTML/PDF results")
args = parser.parse_args()

os.makedirs(args.output, exist_ok=True)

# Find all JSON files generated by Marker (recursively, as Marker often makes subfolders)
json_files = glob.glob(os.path.join(args.input, "**", "*.json"), recursive=True)

if not json_files:
    print(f"No JSON files found in {args.input}")
    exit(0)

for json_path in json_files:
    # Skip metadata/status JSONs that marker might generate
    if "meta.json" in json_path.lower() or "status.json" in json_path.lower():
        continue
        
    base_name = os.path.splitext(os.path.basename(json_path))[0]
    print(f"Processing: {json_path}")
    
    with open(json_path, 'r') as f:
        data = json.load(f)

    page_width, page_height = 612, 792

    # --- SETUP HTML ---
    html_lines = [
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        f"<title>Layout Bounding Boxes - {base_name}</title>",
        "<style>",
        f"  .page {{ position: relative; width: {page_width}px; height: {page_height}px; border: 2px solid black; margin: 20px auto; background: #f9f9f9; }}",
        "  .box { position: absolute; border: 1px solid red; background-color: rgba(255, 0, 0, 0.1); }",
        "</style>",
        "</head>",
        "<body>"
    ]

    # --- SETUP PDF ---
    pdf_path = os.path.join(args.output, f"{base_name}_remediatedPDF.pdf")
    c = canvas.Canvas(pdf_path, pagesize=(page_width, page_height))
    c.setStrokeColorRGB(1, 0, 0)
    c.setFillColorRGB(1, 0, 0, 0.1)

    # Loop through all pages and blocks to draw boxes
    pages = data.get('children', [])
    for page in pages:
        html_lines.append("  <div class='page'>")
        
        blocks = page.get('children', [])
        for block in blocks:
            bbox = block.get('bbox')
            if not bbox:
                continue
                
            x1, y1, x2, y2 = bbox
            box_width = x2 - x1
            box_height = y2 - y1
            
            # HTML BOX (Top-Left)
            html_lines.append(f"    <div class='box' style='left: {x1}px; top: {y1}px; width: {box_width}px; height: {box_height}px;'></div>")
            
            # PDF BOX (Bottom-Left)
            pdf_y = page_height - y2 
            c.rect(x1, pdf_y, box_width, box_height, fill=1)

        html_lines.append("  </div>")
        c.showPage()

    # --- FINALIZE HTML ---
    html_lines.append("</body>")
    html_lines.append("</html>")

    html_path = os.path.join(args.output, f"{base_name}_layout_boxes.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write("\n".join(html_lines))

    # --- FINALIZE PDF ---
    c.save()

    print(f"Successfully generated HTML and PDF for {base_name} in {args.output}")