import json
import os
import glob
import argparse
import re
import html as html_lib
import io
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Paragraph, Frame
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.utils import ImageReader

# For PDF Math Rendering
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg

# --- ARGUMENT PARSING ---
parser = argparse.ArgumentParser(description="Convert Marker JSON to HTML/PDF with Math Rendering.")
parser.add_argument("--input", required=True, help="Directory containing Marker JSON output")
parser.add_argument("--output", required=True, help="Directory to save final HTML/PDF results")
args = parser.parse_args()

os.makedirs(args.output, exist_ok=True)

# Find all JSON files generated by Marker
json_files = glob.glob(os.path.join(args.input, "**", "*.json"), recursive=True)

# PDF Styles Setup
styles = getSampleStyleSheet()
normal_style = styles['Normal']
normal_style.fontSize = 9

def render_latex_to_image(latex_str, font_size=12):
    """Converts a LaTeX string into an image buffer for the PDF."""
    # Simple cleanup for matplotlib's TeX engine
    latex_str = latex_str.replace(r'\ ', ' ')
    
    fig = plt.figure(figsize=(0.1, 0.1)) # Dummy size
    fig.text(0, 0, f"${latex_str}$", fontsize=font_size)
    
    # Draw to buffer
    buf = io.BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight', pad_inches=0.05, transparent=True, dpi=300)
    plt.close(fig)
    buf.seek(0)
    return buf

def prepare_text_content(raw_html):
    """Extracts text and identifies LaTeX math blocks."""
    if not raw_html: return ""
    # Extract LaTeX from <math> tags
    math_content = re.findall(r'<math[^>]*>(.*?)</math>', raw_html, re.DOTALL)
    # Extract plain text from <p> tags
    clean_text = re.sub(r'<[^>]+>', '', raw_html)
    return clean_text.strip(), math_content

for json_path in json_files:
    if "meta.json" in json_path.lower() or "status.json" in json_path.lower():
        continue
        
    base_name = os.path.splitext(os.path.basename(json_path))[0]
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    page_width, page_height = 612, 792

    # --- HTML SETUP ---
    html_lines = [
        "<!DOCTYPE html><html><head>",
        "<script src='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'></script>",
        "<style>",
        f".page {{ position: relative; width: {page_width}px; height: {page_height}px; border: 1px solid #ccc; margin: 10px; background: white; }}",
        # overflow: visible prevents clipping of tall math symbols
        ".box { position: absolute; border: 1px solid rgba(255,0,0,0.3); overflow: visible; font-size: 11px; font-family: serif; }",
        "</style></head><body>"
    ]

    # --- PDF SETUP ---
    pdf_path = os.path.join(args.output, f"{base_name}_rendered.pdf")
    c = canvas.Canvas(pdf_path, pagesize=(page_width, page_height))

    for page in data.get('children', []):
        html_lines.append("<div class='page'>")
        
        for block in page.get('children', []):
            bbox = block.get('bbox')
            raw_html = block.get('html', '')
            if not bbox or not raw_html: continue
            
            x1, y1, x2, y2 = bbox
            bw, bh = x2 - x1, y2 - y1
            pdf_y = page_height - y2
            
            # 1. Update HTML: Wrap content in a span to allow MathJax to expand beyond box if needed
            html_lines.append(f"<div class='box' style='left:{x1}px; top:{y1}px; width:{bw}px; height:{bh}px;'><span>{raw_html}</span></div>")
            
            # 2. Update PDF: Render Math as Images, Text as Paragraphs
            text_only, math_list = prepare_text_content(raw_html)
            
            if block.get('block_type') == 'Equation' and math_list:
                try:
                    img_data = render_latex_to_image(math_list[0])
                    img = ImageReader(img_data)
                    # Center the equation image in the box
                    c.drawImage(img, x1, pdf_y, width=bw, height=bh, preserveAspectRatio=True, mask='auto')
                except:
                    # Fallback to raw text if rendering fails
                    c.setFont("Times-Roman", 8)
                    c.drawString(x1 + 2, pdf_y + 2, text_only[:50])
            else:
                # Standard Text Blocks
                p = Paragraph(html_lib.escape(text_only), normal_style)
                f = Frame(x1, pdf_y, bw, bh, showBoundary=0, leftPadding=1, bottomPadding=1)
                f.addFromList([p], c)

        html_lines.append("</div>")
        c.showPage()

    c.save()
    with open(os.path.join(args.output, f"{base_name}.html"), "w", encoding="utf-8") as f:
        f.write("\n".join(html_lines) + "</body></html>")