import json
import os
import glob
import argparse
import re
import html as html_lib
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, Frame
from reportlab.lib.styles import getSampleStyleSheet

# --- ARGUMENT PARSING ---
parser = argparse.ArgumentParser(description="Convert Marker JSON to HTML/PDF bounding boxes with Text/Math.")
parser.add_argument("--input", required=True, help="Directory containing Marker JSON output")
parser.add_argument("--output", required=True, help="Directory to save final HTML/PDF results")
args = parser.parse_args()

os.makedirs(args.output, exist_ok=True)

# Find all JSON files generated by Marker
json_files = glob.glob(os.path.join(args.input, "**", "*.json"), recursive=True)

if not json_files:
    print(f"No JSON files found in {args.input}")
    exit(0)

# PDF Styles Setup
styles = getSampleStyleSheet()
normal_style = styles['Normal']
normal_style.fontSize = 8
normal_style.leading = 10

def prepare_pdf_text(raw_html):
    """Cleans HTML tags to provide safe raw text/LaTeX for the PDF"""
    if not raw_html:
        return ""
    # Convert <br> tags to literal newlines first
    text = re.sub(r'<br\s*/?>', '\n', raw_html)
    # Strip all other HTML tags (like <p>, <math>, etc.)
    text = re.sub(r'<[^>]+>', '', text)
    # Unescape HTML entities (e.g., &lt; to <)
    text = html_lib.unescape(text)
    # Re-escape specifically for ReportLab's XML-based Paragraph parser
    text = html_lib.escape(text)
    # Convert literal newlines back to <br/> for ReportLab
    text = text.replace('\n', '<br/>')
    return text.strip()

for json_path in json_files:
    # Skip metadata/status JSONs that marker might generate
    if "meta.json" in json_path.lower() or "status.json" in json_path.lower():
        continue
        
    base_name = os.path.splitext(os.path.basename(json_path))[0]
    print(f"Processing: {json_path}")
    
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    page_width, page_height = 612, 792

    # --- SETUP HTML ---
    html_lines = [
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        f"<title>Layout Bounding Boxes - {base_name}</title>",
        # Add MathJax for rendering LaTeX equations
        "<script>window.MathJax = {tex: {inlineMath: [['$', '$'], ['\\\\(', '\\\\)']], displayMath: [['$$', '$$'], ['\\\\[', '\\\\]']]}};</script>",
        '<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>',
        "<style>",
        f"  .page {{ position: relative; width: {page_width}px; height: {page_height}px; border: 2px solid black; margin: 20px auto; background: #f9f9f9; }}",
        "  .box { position: absolute; border: 1px solid red; background-color: rgba(255, 0, 0, 0.05); overflow: hidden; padding: 2px; box-sizing: border-box; font-family: sans-serif; font-size: 12px; }",
        "</style>",
        "</head>",
        "<body>"
    ]

    # --- SETUP PDF ---
    pdf_path = os.path.join(args.output, f"{base_name}_remediatedPDF.pdf")
    c = canvas.Canvas(pdf_path, pagesize=(page_width, page_height))

    # Loop through all pages and blocks to draw boxes and text
    pages = data.get('children', [])
    for page in pages:
        html_lines.append("  <div class='page'>")
        
        blocks = page.get('children', [])
        if blocks:
            for block in blocks:
                bbox = block.get('bbox')
                raw_html = block.get('html', '')
                if not bbox:
                    continue
                    
                x1, y1, x2, y2 = bbox
                box_width = x2 - x1
                box_height = y2 - y1
                
                # --- PROCESS HTML TEXT ---
                # Convert <math> tags to $$ so MathJax natively picks them up
                display_html = re.sub(r'<math[^>]*>', r'$$', raw_html)
                display_html = re.sub(r'</math>', r'$$', display_html)
                
                html_lines.append(f"    <div class='box' style='left: {x1}px; top: {y1}px; width: {box_width}px; height: {box_height}px;'>{display_html}</div>")
                
                # --- PROCESS PDF TEXT ---
                c.setStrokeColorRGB(1, 0, 0)
                c.setFillColorRGB(1, 0, 0, 0.05)
                pdf_y = page_height - y2 
                c.rect(x1, pdf_y, box_width, box_height, fill=1)
                
                text_for_pdf = prepare_pdf_text(raw_html)
                
                if text_for_pdf:
                    # Use Frame and Paragraph to auto-wrap text inside the bounding box
                    frame = Frame(x1, pdf_y, box_width, box_height, leftPadding=2, bottomPadding=2, rightPadding=2, topPadding=2, showBoundary=0)
                    p = Paragraph(text_for_pdf, normal_style)
                    try:
                        frame.addFromList([p], c)
                    except Exception as e:
                        # Fallback if the box is completely too small for the Paragraph layout engine
                        c.setFillColorRGB(0, 0, 0)
                        c.setFont("Helvetica", 6)
                        # Fallback draws a truncated raw string
                        safe_fallback = re.sub(r'<br/>', ' ', text_for_pdf)
                        c.drawString(x1 + 2, page_height - y1 - 8, safe_fallback[:int(box_width/3)] + "...")

        html_lines.append("  </div>")
        c.showPage()

    # --- FINALIZE HTML ---
    html_lines.append("</body>")
    html_lines.append("</html>")

    html_path = os.path.join(args.output, f"{base_name}_layout_boxes.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write("\n".join(html_lines))

    # --- FINALIZE PDF ---
    c.save()

    print(f"Successfully generated HTML and PDF for {base_name} in {args.output}")